import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 * This class represents the user interface of the settings
 * 
 * @author anes_
 */
public class SettingsUI extends javax.swing.JPanel {
    public String ip;
    
    /**
     * Creates new form SettingsUI
     */
    public SettingsUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblPort = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        lblHostName = new javax.swing.JLabel();
        btnChangePort = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblIp = new javax.swing.JLabel();
        txtIp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnConnect1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pc.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 200, 240, 236);

        lblPort.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPort.setForeground(new java.awt.Color(0, 0, 0));
        lblPort.setText("Porta: 5000");
        add(lblPort);
        lblPort.setBounds(260, 310, 190, 37);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1);
        jSeparator1.setBounds(462, 142, 30, 380);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Informazioni Sistema");
        add(jLabel5);
        jLabel5.setBounds(60, 130, 367, 30);

        lblHostName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHostName.setForeground(new java.awt.Color(0, 0, 0));
        lblHostName.setText("Hostname: pc1");
        add(lblHostName);
        lblHostName.setBounds(260, 350, 200, 37);

        btnChangePort.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnChangePort.setText("Cambia Porta");
        btnChangePort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChangePortMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnChangePortMousePressed(evt);
            }
        });
        btnChangePort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePortActionPerformed(evt);
            }
        });
        add(btnChangePort);
        btnChangePort.setBounds(280, 430, 120, 24);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Cancella");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(720, 420, 100, 24);

        lblIp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIp.setForeground(new java.awt.Color(0, 0, 0));
        lblIp.setText("IP: 10.0.1.4");
        add(lblIp);
        lblIp.setBounds(260, 270, 190, 38);
        add(txtIp);
        txtIp.setBounds(700, 270, 120, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Indirizzo IP");
        add(jLabel8);
        jLabel8.setBounds(530, 270, 150, 38);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Configurazione Client");
        add(jLabel10);
        jLabel10.setBounds(467, 130, 420, 30);

        btnConnect1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConnect1.setText("Connetti");
        btnConnect1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConnect1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnConnect1MousePressed(evt);
            }
        });
        btnConnect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnect1ActionPerformed(evt);
            }
        });
        add(btnConnect1);
        btnConnect1.setBounds(550, 420, 100, 24);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Indirizzo IP");
        add(jLabel6);
        jLabel6.setBounds(530, 270, 150, 38);
        add(txtPort);
        txtPort.setBounds(700, 330, 120, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Port");
        add(jLabel9);
        jLabel9.setBounds(530, 330, 150, 38);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangePortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePortMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangePortMouseClicked

    private void btnChangePortMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePortMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnChangePortMousePressed

    private void btnChangePortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangePortActionPerformed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:

        txtIp.setText("");
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnConnect1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnect1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConnect1MouseClicked

    private void btnConnect1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConnect1MousePressed
        // TODO add your handling code here:
        
        String ipAddress = txtIp.getText();

        if(txtIp.getText().length() >=8){
            
            try {
            FileWriter fileWriter = new FileWriter("connectionParam.txt");
            fileWriter.write(ipAddress);
            fileWriter.close();
            
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        JOptionPane.showMessageDialog(this, "Parametri di connessione inseriti con successo", "Conferma", 1);
        }
        else{
            
            JOptionPane.showMessageDialog(this, "Parametri di connessione non validi", "Errore", 2);
        }
        

    }//GEN-LAST:event_btnConnect1MousePressed

    private void btnConnect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnect1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConnect1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePort;
    private javax.swing.JButton btnConnect1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblHostName;
    private javax.swing.JLabel lblIp;
    private javax.swing.JLabel lblPort;
    private javax.swing.JTextField txtIp;
    private javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables
}
