import javax.swing.JOptionPane;

/**
 * This class represents the user interface of the settings
 * 
 * @author anes_
 */
public class StatisticsUI extends javax.swing.JPanel {
    
    /**
     * The statistics manager that updates the statistics
     */
    StatisticsManager statisticsManager;

    /**
     * Creates new form StatisticsUI
     * @param statisticsManager the statistics manager of the application
     */
    public StatisticsUI(StatisticsManager statisticsManager) {
        initComponents();
        this.statisticsManager = statisticsManager;
        this.initStatistics();
    }
    
    /**
     * Initialize the statistics on the GUI
     */
    public void initStatistics(){
        
        txtName.setText("| Ciao " + statisticsManager.getName() + "!");
        lblGame.setText(Integer.toString(statisticsManager.getGamesPlayed()));
        lblWin.setText(Integer.toString(statisticsManager.getGamesWon()));
        lblLost.setText(Integer.toString(statisticsManager.getGamesLost()));
        lblPerc.setText(Double.toString(statisticsManager.getWinPercentage()) + " %");
        lblStreak.setText(Integer.toString(statisticsManager.getWinStreak()));
        lblTime.setText(statisticsManager.getTimePlayed());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblPerc = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblLost = new javax.swing.JLabel();
        lblStreak = new javax.swing.JLabel();
        lblGame = new javax.swing.JLabel();
        lblWin = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtName.setText("| Ciao Edoardo!");
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 240, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/joystick.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 70, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loss.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 70, 80));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Partite Perse:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 130, 80));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText(" Partite Giocate:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 150, 80));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Partite Vinte:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 140, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/time.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 70, 80));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/perc.png"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 70, 80));

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Percentuale vittore:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 190, 80));

        lblPerc.setBackground(new java.awt.Color(51, 51, 51));
        lblPerc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPerc.setForeground(new java.awt.Color(51, 51, 51));
        lblPerc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPerc.setText("0%");
        add(lblPerc, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 430, 90, 80));

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Streak Vittorie: ");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 150, 80));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 20, 330));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/record.png"))); // NOI18N
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 70, 80));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/win.png"))); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 70, 80));

        jLabel15.setBackground(new java.awt.Color(51, 51, 51));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Tempo Giocato:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 180, 80));

        lblTime.setBackground(new java.awt.Color(51, 51, 51));
        lblTime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(51, 51, 51));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setText("00:00");
        add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 60, 80));

        lblLost.setBackground(new java.awt.Color(51, 51, 51));
        lblLost.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLost.setForeground(new java.awt.Color(51, 51, 51));
        lblLost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLost.setText("0");
        add(lblLost, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 60, 80));

        lblStreak.setBackground(new java.awt.Color(51, 51, 51));
        lblStreak.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStreak.setForeground(new java.awt.Color(51, 51, 51));
        lblStreak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStreak.setText("0");
        add(lblStreak, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 60, 80));

        lblGame.setBackground(new java.awt.Color(51, 51, 51));
        lblGame.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGame.setForeground(new java.awt.Color(51, 51, 51));
        lblGame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGame.setText("0");
        add(lblGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 60, 80));

        lblWin.setBackground(new java.awt.Color(51, 51, 51));
        lblWin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblWin.setForeground(new java.awt.Color(51, 51, 51));
        lblWin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWin.setText("0");
        add(lblWin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 60, 80));

        jButton2.setText("Reset Statistiche");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, -1, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        
        int scelta = JOptionPane.showConfirmDialog(null, "Sei sicuro di voler azzerare le statistiche?", "Conferma", JOptionPane.YES_NO_OPTION);
        
        if (scelta == JOptionPane.YES_OPTION) {
            statisticsManager.initializeStatistics();
            this.initStatistics();
        }
    }//GEN-LAST:event_jButton2MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblGame;
    private javax.swing.JLabel lblLost;
    private javax.swing.JLabel lblPerc;
    private javax.swing.JLabel lblStreak;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblWin;
    private javax.swing.JLabel txtName;
    // End of variables declaration//GEN-END:variables
}